### ISSUE TITLE
Error when trying to run in eval mode

### ISSUE THREAD

**Issue by Lan131** [niiceMing/CMTA#3]
I trained CMTA and want to use the model to inference now. logs_fix_50 is the directory I used when I trained CMTA.

 When I try to run it in eval only mode I am getting errors:

export num_envs=50
export HYDRA_FULL_ERROR=1
PYTHONPATH=. python -u ../main.py \
setup=metaworld \
setup.algo=CMTA_info2500_mt${num_envs} \
env=metaworld-mt${num_envs} \
agent=state_sac \
experiment.num_eval_episodes=1 \
experiment.num_train_steps=10\
experiment.eval_only=True \
experiment.random_pos=False \
setup.seed=10 \
setup.dir_name=logs_fix_50 \
replay_buffer.batch_size=1280 \
agent.multitask.num_envs=${num_envs} \
agent.multitask.should_use_disentangled_alpha=True \
agent.multitask.should_use_task_encoder=True \
agent.encoder.type_to_select=moe \
agent.multitask.should_use_multi_head_policy=False \
agent.encoder.moe.task_id_to_encoder_id_cfg.mode=rnn_attention \
agent.encoder.moe.num_experts=6 \
agent.multitask.actor_cfg.should_condition_model_on_task_info=False \
agent.multitask.actor_cfg.should_condition_encoder_on_task_info=True \
agent.multitask.actor_cfg.should_concatenate_task_info_with_encoder=True \
agent.multitask.task_encoder_cfg.model_cfg.pretrained_embedding_cfg.should_use=True \

Traceback (most recent call last):
  File "/home/research/lanier.m/Desktop/CMTA-main/scripts/../main.py", line 18, in <module>
    launch()
  File "/home/research/lanier.m/miniconda3/envs/FairRL/lib/python3.9/site-packages/hydra/main.py", line 32, in decorated_main
    _run_hydra(
  File "/home/research/lanier.m/miniconda3/envs/FairRL/lib/python3.9/site-packages/hydra/_internal/utils.py", line 346, in _run_hydra
    run_and_report(
  File "/home/research/lanier.m/miniconda3/envs/FairRL/lib/python3.9/site-packages/hydra/_internal/utils.py", line 201, in run_and_report
    raise ex
  File "/home/research/lanier.m/miniconda3/envs/FairRL/lib/python3.9/site-packages/hydra/_internal/utils.py", line 198, in run_and_report
    return func()
  File "/home/research/lanier.m/miniconda3/envs/FairRL/lib/python3.9/site-packages/hydra/_internal/utils.py", line 347, in <lambda>
    lambda: hydra.run(
  File "/home/research/lanier.m/miniconda3/envs/FairRL/lib/python3.9/site-packages/hydra/_internal/hydra.py", line 100, in run
    cfg = self.compose_config(
  File "/home/research/lanier.m/miniconda3/envs/FairRL/lib/python3.9/site-packages/hydra/_internal/hydra.py", line 507, in compose_config
    cfg = self.config_loader.load_configuration(
  File "/home/research/lanier.m/miniconda3/envs/FairRL/lib/python3.9/site-packages/hydra/_internal/config_loader_impl.py", line 151, in load_configuration
    return self._load_configuration(
  File "/home/research/lanier.m/miniconda3/envs/FairRL/lib/python3.9/site-packages/hydra/_internal/config_loader_impl.py", line 180, in _load_configuration
    parsed_overrides = parser.parse_overrides(overrides=overrides)
  File "/home/research/lanier.m/miniconda3/envs/FairRL/lib/python3.9/site-packages/hydra/core/override_parser/overrides_parser.py", line 95, in parse_overrides
    raise OverrideParseException(
hydra.errors.OverrideParseException: mismatched input '=' expecting <EOF>
See https://hydra.cc/docs/next/advanced/override_grammar/basic for details

**Comment by yyds-xtt** [comment]
大佬 能发一份跑起来的代码吗 gaozhen610351@163.com

**Comment by yyds-xtt** [comment]
大佬 能发一份跑起来的代码吗 [gaozhen610351@163.com](mailto:gaozhen610351@163.com)

**Comment by yyds-xtt** [comment]
/config/config.yaml 只这样的吗，感觉不太对，一直跑不起来
defaults:
  - setup: metaworld
  - env: metaworld-mt10
  - agent: state_sac
  - logbook: mtrl

experiment:
  name: metaworld-mt10
  num_eval_episodes: 1
  num_train_steps: 2500000
  eval_only: False
  random_pos: False
  save_dir: '/data/zzm/CMTA-main/save_dir'
  builder: mtrl.experiment.multitask.Experiment

replay_buffer:
  batch_size: 1280
agent:
  multitask:
    num_envs: 10
    should_use_disjoint_policy: True
    should_use_disentangled_alpha: True
    should_use_task_encoder: True
    should_use_multi_head_policy: False
    actor_cfg:
      should_condition_model_on_task_info: False
      should_condition_encoder_on_task_info: True
      should_concatenate_task_info_with_encoder: True
    task_encoder_cfg:
      model_cfg:
        pretrained_embedding_cfg:
          should_use: False
  encoder:
    type_to_select: moe
    moe:                   # 添加 moe 部分
      task_id_to_encoder_id_cfg:
        mode: rnn_attention # 配置具体的参数
      num_experts: 6
